### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by Jeansou** [BONNePlayground/NovaHook#2]
```bash
[14:13:16 ERROR]: [Nova] An exception occurred while ticking xyz.xenondevs.nova.machines.tileentity.world.BlockPlacer(Material: machines:block_placer, Location: BlockPos(world=CraftWorld{name=bskyblock_world}, x=2006, y=96, z=-2001), UUID: c49fb067-de59-4924-a2b1-64f78677874e)
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.hasPermission(String)" because "this.sender" is null
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863) ~[guava-31.1-jre.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager.canPlace(ProtectionManager.kt:58) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.machines.tileentity.world.BlockPlacer.handleTick(BlockPlacer.kt:64) ~[?:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$1$1.invoke(TileEntityManager.kt:46) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$1$1.invoke(TileEntityManager.kt:46) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager.init$handleTick(TileEntityManager.kt:38) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager.access$init$handleTick(TileEntityManager.kt:23) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$1.invoke(TileEntityManager.kt:46) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.tileentity.TileEntityManager$init$1.invoke(TileEntityManager.kt:46) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.util.SchedulerUtilsKt.runTaskTimer$lambda$2(SchedulerUtils.kt:28) ~[Nova-0.12.16.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.hasPermission(String)" because "this.sender" is null
        at world.bentobox.bentobox.api.user.User.hasPermission(User.java:281) ~[BentoBox-1.22.1-SNAPSHOT-b2369.jar:?]
        at lv.id.bonne.novahook.protection.NovaProtectionIntegration.checkProtection(NovaProtectionIntegration.java:422) ~[?:?]
        at lv.id.bonne.novahook.protection.NovaProtectionIntegration.checkProtection(NovaProtectionIntegration.java:366) ~[?:?]
        at lv.id.bonne.novahook.protection.NovaProtectionIntegration.canPlace(NovaProtectionIntegration.java:199) ~[?:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager$canPlace$1$1.invoke(ProtectionManager.kt:59) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager$canPlace$1$1.invoke(ProtectionManager.kt:59) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager.checkIntegrations(ProtectionManager.kt:149) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager.checkProtection(ProtectionManager.kt:124) ~[Nova-0.12.16.jar:?]
        at xyz.xenondevs.nova.integration.protection.ProtectionManager.canPlace$lambda$0(ProtectionManager.kt:59) ~[Nova-0.12.16.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.1-jre.jar:?]
        ... 19 more
```

**Comment by Jeansou** [comment]
it still spams when there is no player on the server
